version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__BookDB=Server=db-14669.cvqmuq04evkc.us-east-1.rds.amazonaws.com;Database=Catalog;User Id=admin;Password=Ily0sbek2003
    ports:
      - "5000:80"  # Map host port 5000 to container port 80

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"  # Map host port 80 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the NGINX config file
    depends_on:
      - api  # Ensure NGINX starts after the API service
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
