version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=db-14669.cvqmuq04evkc.us-east-1.rds.amazonaws.com
    ports:
      - "5000:80"
