version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=db-14669.cvqmuq04evkc.us-east-1.rds.amazonaws.com
    ports:
      - "5000:80"

  nginx:
    image: nginx:latest
    container_name: book-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api
